using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL.Mappings
{
    public class PQEmploymentVerMap:EntityTypeConfiguration<PQEmploymentVer>
    {
        public PQEmploymentVerMap()
        {
            this.HasKey(t => t.EmploymentVerRowID);
            this.Property(t => t.EmploymentVerRowID).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            this.Property(t => t.EV_CandidateName).HasMaxLength(100);
            this.Property(t => t.EV_OrganisationName).HasMaxLength(100);
            this.Property(t => t.EV_CmpLocation).HasMaxLength(100);
            this.Property(t => t.EV_CmpNameAddress).HasMaxLength(100);
            this.Property(t => t.EV_EmployeeName).HasMaxLength(100);
            this.Property(t => t.EV_EmployeeCode).HasMaxLength(100);
            this.Property(t => t.EV_EmploymentPeriod).HasMaxLength(100);
            this.Property(t => t.EV_EmploymentDual).HasMaxLength(100);
            this.Property(t => t.EV_EmployedSelf).HasMaxLength(100);
            this.Property(t => t.EV_lappingOver).HasMaxLength(100);
            this.Property(t => t.EV_CandidateTenureWorked).HasMaxLength(100);
            this.Property(t => t.EV_EmployeeTenure).HasMaxLength(100);
            this.Property(t => t.EV_Designation).HasMaxLength(100);
            this.Property(t => t.EV_EmployedEarlierAlso).HasMaxLength(100);
            this.Property(t => t.EV_nature_emplo).HasMaxLength(100);
            this.Property(t => t.EV_typ_employ).HasMaxLength(100);
            this.Property(t => t.EV_EmpType).HasMaxLength(100);
            this.Property(t => t.EV_Department).HasMaxLength(100);
            this.Property(t => t.EV_CmpCost).HasMaxLength(100);
            this.Property(t => t.EV_last_sal).HasMaxLength(100);
            this.Property(t => t.EV_leavingReason).HasMaxLength(200);
            this.Property(t => t.EV_termina).HasMaxLength(200);
            this.Property(t => t.EV_DiscontinueServiceReason).HasMaxLength(200);
            this.Property(t => t.EV_EligibilityforRehire).HasMaxLength(200);
            this.Property(t => t.EV_EligibilityOfRehire).HasMaxLength(200);
            this.Property(t => t.EV_EligibileForRehire).HasMaxLength(200);
            this.Property(t => t.EV_Rhre_Aplcnt_Situt_Ars_Ftre).HasMaxLength(200);
            this.Property(t => t.EV_Reported).HasMaxLength(100);
            this.Property(t => t.EV_ReportingManagerName).HasMaxLength(100);
            this.Property(t => t.EV_Rptng_Mgr_Dsg_Eid_Tno).HasMaxLength(100);
            this.Property(t => t.EV_Rptng_Mgr_Name_Ph).HasMaxLength(100);
            this.Property(t => t.EV_Rptng_Mgr_Name_ConDet).HasMaxLength(100);
            this.Property(t => t.EV_Sub_Rptng_Mgr_Name_Dsg_EidPh).HasMaxLength(100);
            this.Property(t => t.EV_Supervisor).HasMaxLength(100);
            this.Property(t => t.EV_Sup_Name_Dsg).HasMaxLength(100);
            this.Property(t => t.EV_FormalitiesExit).HasMaxLength(200);
            this.Property(t => t.EV_FullFinalFormalities).HasMaxLength(200);
            this.Property(t => t.EV_ExitFormalitiesPending).HasMaxLength(200);
            this.Property(t => t.EV_HandledResponsibilities).HasMaxLength(200);
            this.Property(t => t.EV_ResponsibilitiesHandled).HasMaxLength(200);
            this.Property(t => t.EV_OverallJobPerformance).HasMaxLength(200);
            this.Property(t => t.EV_PerfromanceLevel).HasMaxLength(200);
            this.Property(t => t.EV_KnowledgeProcess).HasMaxLength(200);
            this.Property(t => t.EV_ValidationBusinessOperation).HasMaxLength(200);
            this.Property(t => t.EV_DutiesNature).HasMaxLength(200);
            this.Property(t => t.EV_Prof_Ablts_Aplcnt).HasMaxLength(200);
            this.Property(t => t.EV_Dsplnry_Perf_Iss_Rptd).HasMaxLength(200);
            this.Property(t => t.EV_DisciplinaryIssue).HasMaxLength(200);
            this.Property(t => t.EV_Cmplnts_Rslt_Dsplnry_Sub).HasMaxLength(200);
            this.Property(t => t.EV_Emp_Invol_Fraud_Actvty).HasMaxLength(200);
            this.Property(t => t.EV_PerformanceIssues).HasMaxLength(200);
            this.Property(t => t.EV_TeamConduct).HasMaxLength(200);
            this.Property(t => t.EV_TeamPlayerNot).HasMaxLength(200);
            this.Property(t => t.EV_TechnologicalKnowledge).HasMaxLength(200);
            this.Property(t => t.EV_Fback_Accnt_Cduct_Jb).HasMaxLength(200);
            this.Property(t => t.EV_DisciplinedHowHe).HasMaxLength(200);
            this.Property(t => t.EV_LongKnown).HasMaxLength(200);
            this.Property(t => t.EV_LongWork).HasMaxLength(200);
            this.Property(t => t.EV_LeavesTook).HasMaxLength(200);
            this.Property(t => t.EV_People_Rptd).HasMaxLength(200);
            this.Property(t => t.EV_Conduct).HasMaxLength(200);
            this.Property(t => t.EV_Performance).HasMaxLength(200);
            this.Property(t => t.EV_Perf_Rate).HasMaxLength(100);
            this.Property(t => t.EV_Mtng_Deadline).HasMaxLength(100);
            this.Property(t => t.EV_Comm_Skills).HasMaxLength(100);
            this.Property(t => t.EV_Wrtn_Comm_Skills).HasMaxLength(100);
            this.Property(t => t.EV_Verb_Comm_Skills).HasMaxLength(100);
            this.Property(t => t.EV_Procs_Knowlg).HasMaxLength(100);
            this.Property(t => t.EV_Attdnce_Punct).HasMaxLength(100);
            this.Property(t => t.EV_Ldrshp_Qualty).HasMaxLength(100);
            this.Property(t => t.EV_Mngng_Mtng_Int_Cust_Expect).HasMaxLength(100);
            this.Property(t => t.EV_OtherIssues).HasMaxLength(200);
            this.Property(t => t.EV_AdherenceTAT).HasMaxLength(200);
            this.Property(t => t.EV_CompletesTATWork).HasMaxLength(200);
            this.Property(t => t.EV_Atude_Hon_Per_Aplcnt).HasMaxLength(200);
            this.Property(t => t.EV_WorkAttitude).HasMaxLength(100);
            this.Property(t => t.EV_RatingTeaming).HasMaxLength(100);
            this.Property(t => t.EV_Rate_Tech).HasMaxLength(100);
            this.Property(t => t.EV_AttendancePunctuality).HasMaxLength(100);
            this.Property(t => t.EV_Cmnts_Abt_Sub).HasMaxLength(100);
            this.Property(t => t.EV_SubjectComments).HasMaxLength(100);
            this.Property(t => t.EV_AdditionalComments).HasMaxLength(100);
            this.Property(t => t.EV_OtherComments).HasMaxLength(100);
            this.Property(t => t.EV_OtherRemarks).HasMaxLength(100);
            this.Property(t => t.EV_AttachedDocumentGenuine).HasMaxLength(100);
            this.Property(t => t.EV_ResponseMode).HasMaxLength(100);
            this.Property(t => t.EV_RefereeResponse).HasMaxLength(100);
            this.Property(t => t.EV_RespondentName).HasMaxLength(100);
            this.Property(t => t.EV_RefereeDetails).HasMaxLength(100);
            this.Property(t => t.EV_RespondentDesignation).HasMaxLength(100);
            this.Property(t => t.EV_RefereeNameDetails).HasMaxLength(200);
            this.Property(t => t.EV_DetailsReferee).HasMaxLength(200);
            this.Property(t => t.EV_ContactDetail).HasMaxLength(200);
            this.Property(t => t.EV_Verfson_Poss_Phy_Visit).HasMaxLength(100);
            this.Property(t => t.EV_Details_Verfson_EidPh_Phyvst).HasMaxLength(200);
            this.Property(t => t.EV_Nme_Add_Cmpny_Exist_Now).HasMaxLength(200);
            this.Property(t => t.EV_Name_Dsg_Verfyng_Auth).HasMaxLength(200);
            this.Property(t => t.EV_Verified).HasMaxLength(200);
            this.Property(t => t.EV_Verified_by).HasMaxLength(200);
            this.Property(t => t.EV_Verified_by_dsg_ConNo).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails6).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails7).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails8).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails9).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails10).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails11).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails12).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails13).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails14).HasMaxLength(200);
            this.Property(t => t.EV_OtherDetails15).HasMaxLength(200);
            this.Property(t => t.ATA_Reverse_Directory).HasMaxLength(200);
            this.Property(t => t.ATA_Residcl_Commrcl).HasMaxLength(200);
            this.Property(t => t.ATA_Stock_Exchnge).HasMaxLength(200);
            this.Property(t => t.ATA_Telphne_Directry_Srch).HasMaxLength(200);
            this.Property(t => t.ATA_Yellow_Pages).HasMaxLength(200);
            this.Property(t => t.ATA_Who_Domain).HasMaxLength(200);
            this.Property(t => t.ATA_GoogleSearch).HasMaxLength(200);
            this.Property(t => t.ATA_InfrastructureOfCmp).HasMaxLength(200);
            this.Property(t => t.ATA_Just_Dial).HasMaxLength(200);
            this.Property(t => t.ATA_Neighbor_Check1).HasMaxLength(200);
            this.Property(t => t.ATA_NASCOM_Empanelment).HasMaxLength(200);
            this.Property(t => t.ATA_Photograph).HasMaxLength(200);
            this.Property(t => t.ATA_Physical_Site).HasMaxLength(200);
            this.Property(t => t.ATA_Reg_Company).HasMaxLength(200);
            this.Property(t => t.ATA_PO_Courier_Check).HasMaxLength(200);
            this.Property(t => t.ATA_Network_Sol).HasMaxLength(200);
            this.Property(t => t.ATA_ApprxEmpWorking).HasMaxLength(200);
            this.Property(t => t.ATA_CID_No).HasMaxLength(100);
            this.Property(t => t.ATA_Cmpny_Addr).HasMaxLength(100);
            this.Property(t => t.ATA_Decoy_Call).HasMaxLength(200);
            this.Property(t => t.ATA_Cmpny_Website).HasMaxLength(200);

            this.Property(a => a.TypeRevert).HasMaxLength(50);
            this.Property(a => a.CheckStatus).HasMaxLength(50);
            this.Property(a => a.Severity).HasMaxLength(50);
            this.Property(a => a.ColorName).HasMaxLength(50);
            this.Property(a => a.ReportComments).HasMaxLength(3000);

            this.Property(a => a.VerifierDesignation).HasMaxLength(100);
            this.Property(a => a.VerifierContactNo).HasMaxLength(20);
            this.Property(a => a.VerifierMobileNo).HasMaxLength(20);
            this.Property(a => a.VerifierEmailId).HasMaxLength(100);

            this.HasRequired(c => c.PQEmployment).WithMany().HasForeignKey(c => c.EmploymentRowID).WillCascadeOnDelete(false);
        }
    }
}
