using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL.Mappings
{
    public class PQIndianDatabaseVerMap:EntityTypeConfiguration<PQIndianDatabaseVer>
    {
        public PQIndianDatabaseVerMap()
        {
            this.HasKey(i => i.IndianDatabaseVerRowID);
            this.Property(i => i.IndianDatabaseVerRowID).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
           
            this.Property(i=>i.IDC_CBI_Most_Wanted                  ).HasMaxLength(200);
            this.Property(i=>i.IDC_Cibil_Database                   ).HasMaxLength(200);
            this.Property(i=>i.IDC_Compliance_Check                 ).HasMaxLength(200);
            this.Property(i=>i.IDC_Cross_Directorship_Db            ).HasMaxLength(200);
            this.Property(i=>i.IDC_Directorship_Watch_List          ).HasMaxLength(200);
            this.Property(i=>i.IDC_Financ_Authorities_Db            ).HasMaxLength(200);
            this.Property(i=>i.IDC_Highcourt                        ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Specific_Media_Search         ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Specific_Web_Media_Search     ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Specific_Web_Search           ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Political_Expsd_Per_Db        ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Prosecuted_Cmpny_Db           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Interpol_Most_Wanted             ).HasMaxLength(200);
            this.Property(i=>i.IDC_Magistrate_Court                 ).HasMaxLength(200);
            this.Property(i=>i.IDC_MCA_Vansh_Cmpny_Db               ).HasMaxLength(200);
            this.Property(i=>i.IDC_Regltry_Authrty_Check            ).HasMaxLength(200);
            this.Property(i=>i.IDC_SEBI                             ).HasMaxLength(200);
            this.Property(i=>i.IDC_St_Police_Most_Want              ).HasMaxLength(200);
            this.Property(i=>i.IDC_Supreme_Court                    ).HasMaxLength(100);
            this.Property(i=>i.IDC_Time_Verification                ).HasMaxLength(100);
            this.Property(i=>i.IDC_Tribunals                        ).HasMaxLength(200);
            this.Property(i=>i.IDC_Verfr_Cmmnts                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_Most_Want_Criminals              ).HasMaxLength(200);
            this.Property(i=>i.IDC_Supreme_Court_Record_Check       ).HasMaxLength(200);
            this.Property(i=>i.IDC_Tribunal                         ).HasMaxLength(200);
            this.Property(i=>i.IDC_Debt_Recovery_Db                 ).HasMaxLength(200);
            this.Property(i=>i.IDC_Loan_Defaulters_List_RBI         ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Court_Db                      ).HasMaxLength(200);
            this.Property(i=>i.IDC_Any_Other_Cmmnts_IDC             ).HasMaxLength(200);
            this.Property(i=>i.IDC_Civil_Court_Action               ).HasMaxLength(200);
            this.Property(i=>i.IDC_Civil_Litig_Db_Check             ).HasMaxLength(200);
            this.Property(i=>i.IDC_Crrpt_Offcrs_Db                  ).HasMaxLength(200);
            this.Property(i=>i.IDC_Criminal_Verf                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_Directrshp_Watchlist             ).HasMaxLength(200);
            this.Property(i=>i.IDC_Highcourt_Cases                  ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_Specific_Internet_Srch        ).HasMaxLength(200);
            this.Property(i=>i.IDC_Internet_Srch                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_Media_Srch                       ).HasMaxLength(200);
            this.Property(i=>i.IDC_Bribery_Corrup                   ).HasMaxLength(200);
            this.Property(i=>i.IDC_Financ_Irregularties             ).HasMaxLength(200);
            this.Property(i=>i.IDC_Fraud                            ).HasMaxLength(200);
            this.Property(i=>i.IDC_Intellect_Proprty_Viol           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Money_Laund                      ).HasMaxLength(200);
            this.Property(i=>i.IDC_Insider_Trading                  ).HasMaxLength(200);
            this.Property(i=>i.IDC_Director_Name                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_Arbitration_Concilation          ).HasMaxLength(200);
            this.Property(i=>i.IDC_Centeral_Vgilance_Db             ).HasMaxLength(200);
            this.Property(i=>i.IDC_Civil_Litigation_Dbcheck         ).HasMaxLength(200);
            this.Property(i=>i.IDC_CmpLawViolations                 ).HasMaxLength(200);
            this.Property(i=>i.IDC_Consumer_Protect_Viol            ).HasMaxLength(200);
            this.Property(i=>i.IDC_Cr_Reput_Risk_Dbcheck_In         ).HasMaxLength(200);
            this.Property(i=>i.IDC_Crime_Record_Dbcheck_In          ).HasMaxLength(200);
            this.Property(i=>i.IDC_Direct_Tax_Viol                  ).HasMaxLength(200);
            this.Property(i=>i.IDC_Enviromnt_Prot_Viol              ).HasMaxLength(200);
            this.Property(i=>i.IDC_Excise_Custom_Viol               ).HasMaxLength(200);
            this.Property(i=>i.IDC_Financ_Crime_Invst_Db            ).HasMaxLength(200);
            this.Property(i=>i.IDC_IndianDatabases                  ).HasMaxLength(200);
            this.Property(i=>i.IDC_Labor_Service_Law_Viol           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Sales_Tax_Viol                   ).HasMaxLength(200);
            this.Property(i=>i.IDC_Serious_Organized_Crime          ).HasMaxLength(200);
            this.Property(i=>i.IDC_Cibil_Other_CR_Bureau            ).HasMaxLength(200);
            this.Property(i=>i.IDC_Political_Expsd_Per_Db           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Dept_Cmpny_Affair_Vansh_DB       ).HasMaxLength(200);
            this.Property(i=>i.IDC_Board_Indus_Financ_Reconst       ).HasMaxLength(200);
            this.Property(i=>i.IDC_Worldcheck_In_Db                 ).HasMaxLength(100);
            this.Property(i=>i.IDC_CBI                              ).HasMaxLength(200);
            this.Property(i=>i.IDC_Sales_Tax_Viol_IDC               ).HasMaxLength(200);
            this.Property(i=>i.IDC_Competition_Commison_In          ).HasMaxLength(200);
            this.Property(i=>i.IDC_Cntrl_VgilnceCommison_Db         ).HasMaxLength(200);
            this.Property(i=>i.IDC_In_MHA_Ban_Org                   ).HasMaxLength(200);
            this.Property(i=>i.IDC_Labour_Service_Law_Viol          ).HasMaxLength(200);
            this.Property(i=>i.IDC_IN_NIA                           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Consumer_Protect_Viol_IDC        ).HasMaxLength(200);
            this.Property(i=>i.IDC_RBI                              ).HasMaxLength(200);
            this.Property(i=>i.IDC_Envirmtnl_Protect_Viol           ).HasMaxLength(200);
            this.Property(i=>i.IDC_RBI_Sanction_Notice              ).HasMaxLength(200);
            this.Property(i=>i.IDC_Arbitration_Concilation_IDC      ).HasMaxLength(200);
            this.Property(i=>i.IDC_RBI_Vansh_Financ_Cmpny           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Direct_Tax_Violation             ).HasMaxLength(200);
            this.Property(i=>i.IDC_SEBI_IDC                         ).HasMaxLength(200);
            this.Property(i=>i.IDC_Excise_Custom_Viol_IDC           ).HasMaxLength(200);
            this.Property(i=>i.IDC_Cmpny_Law_Viol                   ).HasMaxLength(200);
            this.Property(i=>i.IDC_Sc_Hc_Records_Incl_Tribunal      ).HasMaxLength(200);
            this.Property(i=>i.IDC_INCB                             ).HasMaxLength(200);
            this.Property(i=>i.IDC_INTDL                            ).HasMaxLength(200);
            this.Property(i=>i.IDC_INWCCB                           ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks1                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks2                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks3                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks4                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks5                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks6                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks7                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks8                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks9                     ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks10                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks11                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks12                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks13                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks14                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks15                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks16                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks17                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks18                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks19                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks20                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks21                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks22                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks23                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks24                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks25                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks26                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks27                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks28                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks29                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks30                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks31                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks32                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks33                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks34                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks35                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks36                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks37                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks38                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks39                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks40                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks41                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks42                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks43                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks44                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks45                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks46                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks47                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks48                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks49                    ).HasMaxLength(200);
            this.Property(i=>i.IDC_OtherChecks50                    ).HasMaxLength(200);
            this.Property(i=>i.ATA_Reverse_Directory                ).HasMaxLength(200);
            this.Property(i=>i.ATA_Residcl_Commrcl                  ).HasMaxLength(200);
            this.Property(i=>i.ATA_Stock_Exchnge                    ).HasMaxLength(200);
            this.Property(i=>i.ATA_Telphne_Directry_Srch            ).HasMaxLength(200);
            this.Property(i=>i.ATA_Yellow_Pages                     ).HasMaxLength(200);
            this.Property(i=>i.ATA_Who_Domain                       ).HasMaxLength(200);
            this.Property(i=>i.ATA_GoogleSearch                     ).HasMaxLength(200);
            this.Property(i=>i.ATA_InfrastructureOfCmp              ).HasMaxLength(200);
            this.Property(i=>i.ATA_Just_Dial                        ).HasMaxLength(200);
            this.Property(i=>i.ATA_Neighbor_Check1                  ).HasMaxLength(200);
            this.Property(i=>i.ATA_NASCOM_Empanelment               ).HasMaxLength(200);
            this.Property(i=>i.ATA_Photograph                       ).HasMaxLength(200);
            this.Property(i=>i.ATA_Physical_Site                    ).HasMaxLength(200);
            this.Property(i=>i.ATA_Reg_Company                      ).HasMaxLength(200);
            this.Property(i=>i.ATA_PO_Courier_Check                 ).HasMaxLength(200);
            this.Property(i=>i.ATA_Network_Sol                      ).HasMaxLength(200);
            this.Property(i=>i.ATA_ApprxEmpWorking                  ).HasMaxLength(200);
            this.Property(i=>i.ATA_CID_No                           ).HasMaxLength(200);
            this.Property(i=>i.ATA_Cmpny_Addr                       ).HasMaxLength(200);
            this.Property(i => i.ATA_Decoy_Call).HasMaxLength(200);


            this.Property(a => a.TypeRevert).HasMaxLength(20);
            this.Property(a => a.CheckStatus).HasMaxLength(20);
            this.Property(a => a.CaseStatus).HasMaxLength(20);
            this.Property(a => a.ColorName).HasMaxLength(20);
            this.Property(a => a.Remarks).HasMaxLength(200);

            this.Property(a => a.VerifierDesignation).HasMaxLength(100);
            this.Property(a => a.VerifierContactNo).HasMaxLength(20);
            this.Property(a => a.VerifierMobileNo).HasMaxLength(20);
            this.Property(a => a.VerifierEmailId).HasMaxLength(100);

            this.HasRequired(c => c.PQIndianDatabase).WithMany().HasForeignKey(c => c.IndianDatabaseRowID).WillCascadeOnDelete(false);
        }
    }
}
